### PR TITLE
327255 improve deployments page

### PR DESCRIPTION
**Pull request by feedmypixel**
Work to fix the following UX issues:

- As a user I don't know the version of the work I have just merged
- As a user how do I know what work is in a version
- As a user unless I look on the Running Services page I don't know what version of my service has already been deployed and in which environment

## Highlights
- We have a new Vanilla JavaScript progressive and accessible Autocomplete component
- The above component once battle tested for a few weeks can be rolled out across the Portal Frontend
- More information is displayed to users on the deploy service page to help them answer the above questions
- We have relative date functionality, this has been rolled out across the Portal Frontend
- Added `.browserslistrc`
- `autocompleteSearch` and `autocompleteDropdown` components have been removed (they are not currently used) and can be replaced by the `autocomplete` component
- Created a simple CSS tooltip

## Associated PR
https://github.com/DEFRA/cdp-portal-backend/pull/117

## Demo
deploy-service-improvements

deploy-service-details-page

<hr />

## Autocomplete
Various bits of functionality from the autocomplete

Screenshot 2024-03-13 at 17 39 48
Screenshot 2024-03-13 at 17 39 55
Screenshot 2024-03-13 at 17 40 05
Screenshot 2024-03-13 at 18 50 43

Screenshot 2024-03-13 at 19 18 07

<hr />

## Tooltip
Simple `CSS` tooltip

Screenshot 2024-03-14 at 22 28 43

### CODE REVIEW

**Review by flurdy — APPROVED** [review]

**Comment by flurdy** [comment]
Seems good

**Comment by flurdy** [comment]
> As a user unless I look on the Running Services page I don't know what version of my service has already been deployed and in which environment

This part is already solved on the individual service page, as well. I like showing in deploy as well though

**Comment by flurdy** [comment]
Maybe title the right hand info with the service? It is mentioned in the github link but in case of a slow update it may be out of sync with the drop down?

**Comment by feedmypixel** [comment]
> Maybe title the right hand info with the service? It is mentioned in the github link but in case of a slow update it may be out of sync with the drop down?

I have added more context to provide the user with details for which service the versions are reffering to

Screenshot 2024-03-14 at 20 32 57

**Pull request merged**
